config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:new, :create]
  
  get "search_results", to: "toppages#search_results"
  
  resources :preservations, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/preservation.rb
class Preservation < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :content_sentence, presence: true, length: { maximum: 255 }
  validates :content_signals, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence:true, length: { maximum: 50 }
    has_secure_password
    has_many :preservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/preservations_controller.rb
class PreservationsController < ApplicationController
  
  def index
    if logged_in?
      @preservations = current_user.preservations.order(:id).page(params[:page])
    end 
  end

  def show
    @preservation = current_user.preservations.find(params[:id])
  end

  def new
    @preservation = current_user.preservations.new
    search_results
    
  
  end

  def create
    @preservation = current_user.preservations.build(preservation_params)
    if @preservation.save
      flash[:success] = "保存成功"
      redirect_to root_url
    else
      @preservation = current_user.preservations.new
      flash[:danger] = "保存失敗"
      render "preservations/new"
    end
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end 
  def logged_in?
    !!current_user
  end 

  def preservation_params
    params.require(:preservation).permit(:title, :content_sentence, :content_signals)
  end 
end
def search_results
    @word = params[:search_word]
    
    require "unirest"

    response = Unirest.get "https://wordsapiv1.p.rapidapi.com/words/#{@word}",
    headers:{
      "X-RapidAPI-Host" => "wordsapiv1.p.rapidapi.com",
      "X-RapidAPI-Key" => "5686a7df03msh2d311fd7a2aa48ep193105jsn2d65e7d6a423"
    }
    
    @signals = response.body["pronunciation"]["all"]

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name].downcase
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = "ログイン成功"
      redirect_to root_url
    else
      flash.now[:danger] = "ログイン失敗"
      render "new"
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウト完了"
    redirect_to root_url
  end
  
  private
  def login(name, password)
    @user = User.find_by(name: name)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end 
  end 
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def search_results
    @word = params[:search_word]
    
    require "unirest"

    response = Unirest.get "https://wordsapiv1.p.rapidapi.com/words/#{@word}",
    headers:{
      "X-RapidAPI-Host" => "wordsapiv1.p.rapidapi.com",
      "X-RapidAPI-Key" => "5686a7df03msh2d311fd7a2aa48ep193105jsn2d65e7d6a423"
    }
    
    @signals = response.body["pronunciation"]["all"]

  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザ登録成功"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザ登録失敗"
      render :new
    end 
  end
  private
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    private
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end 
    end 
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end 
    def logged_in?
        !!current_user
    end 
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="/">Protranslate</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-targer="#navbarSupportContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportContent">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                <% if logged_in? %>
                    
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class= "dropdown-item"><%= link_to "ファイル一覧", preservations_path %></li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item"><%= link_to "会員登録", signup_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログイン", login_path,  class: "nav-link" %></li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protranslate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
  
      <%= yield %>
    </div>
  </body>
</html>

app/views/preservations/create.html.erb
<h1>Preservations#create</h1>
<p>Find me in app/views/preservations/create.html.erb</p>

app/views/preservations/index.html.erb
<% if flash[:success] %>
    <div class="success">
        <%= flash[:success] %>
    </div>
<% end %>

<ul class="list-unstyled">
    <li>
        <% @preservations.each do |preservation| %>
            <div>
                <p><%= link_to preservation.title, preservation %></p>
            </div>
        <% end %>
    </li>
</ul>

app/views/preservations/new.html.erb
<% if flash[:danger] %>
  <div class="danger">
    <%= flash[:danger] %>
  </div>
<% end  %>
  <div>
    <%= form_with(model: @preservation, local: true) do |f| %>
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title %>
    
    <h3>保存する英単語：<%= @word %></h3>
    <h3>保存する発音記号：<%= @signals %></h3>

    <div class="text-center">
      <%= f.submit '保存' %>
    </div>
  
    <% end %>
  </div>

app/views/preservations/show.html.erb
<ul class="list-unstyled">
    <li><%= @preservation.title %></li>
    <li><%= @preservation.content_sentence %></li>
    <li><%= @preservation.content_signals %></li>
</ul>

app/views/toppages/index.html.erb
<div class="text-center">
    <p>英語の勉強に発音記号は不可欠！</p>
    <p>早速調べよう！</p>
    <p>英単語を入力しよう</p>

    <%= form_with(url: search_results_path, local: true, method: :get) do |f| %>
        <%= text_field_tag :search_word %><br>
        <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>

    
    
    <% if logged_in? %>
        <p>英語学習頑張って</p>
    <% else %>
        <p>会員登録をすると以下のことができるようになります</p>
        <p> 英単語・発音記号を保存する</p><br>
        <p> 保存したファイルの閲覧</p><br>
        <p>会員登録は無料でできます</p><br>
        <p>会員登録ボタンから会員登録をしよう</p><br>
        <div class="form-group row">
            <label class="col-sm-2">こちらから→</label>
            <div class="col-sm-10">
               <%= link_to "会員登録", signup_path, class: "btn btn-lg btn-primary" %> 
            </div>
        
        </div>
    <% end %>
</div>

app/views/toppages/search_results.html.erb
<div class="text-center">
    <p>英語の勉強に発音記号は不可欠！</p>
    <p>確認してみよう！</p>
    <p>英単語：<%= @word %></p>
    <p>発音記号：<%= @signals %></p>
    <%= link_to "戻る", root_path, class: "btn btn-lg btn-primary" %>
    
        <% if logged_in? %>
            <center><%= link_to "保存確認へ", new_preservation_path(search_word: @word, tango: @signals) %></center>
        <% else %>
            <p>会員登録をすると以下のことができるようになります</p>
            <p> 英単語・発音記号を保存する</p>
            <p> 保存したファイルの閲覧</p>
            <p>会員登録は無料でできます</p>
            <p>ログインボタンから会員登録をしよう</p>
            <div class="form-group row">
                <label class="col-sm-2">既に登録済の方→</label>
                <div class="col-sm-10">
                   <%= link_to "ログイン", signup_path, class: "btn  btn-primary" %> 
                </div>
            </div>
        <% end %>

</div>
    

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
    <h3>会員登録をしましょう</h3>
</div>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render "layouts/error_messages", model: f.object %>
            <div class="form-group">
                <%= f.label :name, "名前" %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password, "パスワード" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation, "確認" %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <div class="text-center">
                <%= f.submit "会員登録", class: "btn btn-primary " %>
            </div>
        <% end %>
        
    </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>